### ISSUE TITLE
Criação da API

### ISSUE THREAD

**Issue by allangrds** [allangrds/AdonisJS-JWT-Simple-API#1]
# Tasks
- Necessita estar autenticado
- [x] GET /tasks 200 | 401
  - [x] pagination
  - [x] filter by title or description
- [x] GET /tasks/{id} 200 | 404 | 401
- [x] POST /tasks 201 | 400 | 401
  - [x] Title
    - [x] Required
    - [x] Max: 30
  - [x] Description
    - [x] Required
    - [x] Max: 255
- [x] PATCH /tasks/{id} 202 | 400 | 404 | 401
  - [x] Title
    - [x] Required
    - [x] Max: 30
  - [x] Description
    - [x] Required
    - [x] Max: 255
- [x] DELETE /tasks/{id} 204 |  404 | 401
  
# Auth
- [x] POST /auth/login 200 | 400 | 401
  - [x] email
    - [x] Required
    - [x] Max: 30
  - [x] password
    - [x] Required
    - [x] Max: 30

- [x] POST /auth/logout 200 | 401
  - [x] token
    - [x] Required

- [x] POST /auth/refresh 200 | 401
  - [x] token
    - [x] Required
    
# Outros
- [ ] GET /user 200 | 401
  - Necessita estar autenticado
- [x] POST /users 200 | 401
     
obs: colocar rate limit em todas as rotas

**Comment by allangrds** [comment]
Pra migration

```php
$table->string('title', 50);
$table->text('description', 255);
```
